name: Generate a build and push to dev_build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # Le build de ton projet

      - name: List files in build folder
        run: ls -al dist  # Vérifie que tous les fichiers sont générés dans 'dist'

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dev_build   # La branche où tu veux pousser les fichiers
          FOLDER: dist        # Répertoire 'dist' comme répertoire d'output
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
