name: Deploy React App to Hostinger

on:
  push:
    branches:
      - master  # Changez cela en votre branche principale, par exemple 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Utilisez la version Node.js que vous préférez

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Hostinger
        uses: s0/git-publish-subdir-action@develop
        with:
          repository: Apalian/portfolio
          branch: build
          token: ${{ secrets.GH_TOKEN }}
          folder: build
